[package]
name = "soul-lantern-mc-debug"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls", "system-proxy"] }
ring = "0.17"
zip = { version = "2", default-features = false, features = ["deflate"] }
tar = "0.4"
flate2 = "1"
tempfile = "3"
uuid = { version = "1", features = ["v4"] }
