import assert from 'node:assert/strict';
import { getItemCatalog, getEntityCatalog, getEnchantmentCatalog, getEffectCatalog, getAttributeCatalog, unsupportedItemMessage } from './catalogs.ts';
import { createDefaultForm, buildGiveCommand, parseStoredForm } from './builder.ts';
import { buildSystemPrompt } from './ai/prompt.ts';
assert(!getItemCatalog('java_1_20_5').some(row => row[0] === 'minecraft:diamond_spear'));
assert(!getItemCatalog('java_1_20_5').some(row => row[0] === 'minecraft:mace'));
assert(getItemCatalog('java_1_21').some(row => row[0] === 'minecraft:mace'));
assert(getItemCatalog('java_26_3_plus').some(row => row[0] === 'minecraft:diamond_spear'));
assert(getEntityCatalog('java_1_21').some(row => row[0] === 'minecraft:boat'));
assert(!getEntityCatalog('java_26_3_plus').some(row => row[0] === 'minecraft:boat'));
assert(!getEnchantmentCatalog('java_1_21').some(row => row[0] === 'minecraft:lunge'));
assert(getEnchantmentCatalog('java_26_3_plus').some(row => row[0] === 'minecraft:lunge'));
assert(getEffectCatalog('java_26_3_plus').some(row => row[0] === 'minecraft:breath_of_the_nautilus'));
assert.equal(getAttributeCatalog('java_26_3_plus').length, 40);
const form = createDefaultForm();
form.version = 'java_1_20_5';
form.item = 'minecraft:diamond_spear';
assert.throws(() => buildGiveCommand(form), /不属于/);
assert.equal(form.item, 'minecraft:diamond_spear');
assert.equal(unsupportedItemMessage('java_1_20_5', 'mymod:spear'), null);
form.item = 'mymod:spear';
assert(buildGiveCommand(form).includes('mymod:spear'));
form.version = 'java_26_3_plus';
assert.equal(parseStoredForm(form).version, 'java_26_3_plus');
const older = buildSystemPrompt('java_1_21');
assert(older.includes('Minecraft 1.21 官方'));
assert(!older.includes('minecraft:lunge'));
assert(!older.includes('nbt={data:'));
assert(buildSystemPrompt('java_26_3_plus').includes('block_state:{id:'));
console.log('版本目录、草稿保留、自定义命名空间和提示词检查通过');
